### ISSUE TITLE
Close left open process in dcrtxclient

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#1]
There appears to be many conditions that will cause dcrwallet to be left in a waiting state without completing the ticket purchase. When this happens, additional ticket purchasing is blocked. Exiting the app is also blocked, CTRL-C will display "DCRW: Shutdown signaled. Already shutting down..." but it will still wait and not close the app.

Shutting down the joind server will unblock the dcrwallet clients, so it may be stuck waiting for a server response.

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/6f6007427ab8297a09216109e2b6ef8eebae48d3

**Comment by raedah** [comment]
Some of these have been fixed. I will open new issues for remaining cases.
