### ISSUE TITLE
Use timer to send join

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#12]
Delete the maxparticipants option in dcrtxmatcher, and instead set a send timer that will cause the joined splittx to be sent every x minutes. This way the joins will happen for any number of participants.

**Comment by huyntsgs** [comment]
Should keep maxparticipants to control max participants can join in and combine with timer, which condition is met first then joining will be processed. Too much participants in one split tx looks like not nice

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/8ce2455bafd001d943ff2cdec6847d5273c86e3f, https://github.com/raedahgroup/dcrtxmatcher/commit/0a49ea1ae1965f53a0e547b649cb46d2ab50a22a and https://github.com/raedahgroup/dcrwallet/commit/5db3d8ff354b38372ad743e6b9cf54092cdfd061

**Comment by raedah** [comment]
More participants = better privacy

**Comment by raedah** [comment]
verified working
