### ISSUE TITLE
CTRL-C should cleanly terminate connection to dcrtxmatcher

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#17]
Currently if a client is "Waiting for enough participants...", and they CTRL-C to exit dcrwallet, they will get to '[INF] TKBY: Stopping ticket buyer' where they will be stuck waiting indefinitely. The work around is to kill the dcrtxmatcher server, but the desired behavior is for a client to be able to cleanly close its connection to the server and exit.

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/8ce2455bafd001d943ff2cdec6847d5273c86e3f, https://github.com/raedahgroup/dcrtxmatcher/commit/0a49ea1ae1965f53a0e547b649cb46d2ab50a22a and https://github.com/raedahgroup/dcrwallet/commit/5db3d8ff354b38372ad743e6b9cf54092cdfd061

**Comment by raedah** [comment]
verified resolved
