### ISSUE TITLE
Client is connecting to server at startup

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#18]
When I start the client instance, I see
[INF] GRPC: pickfirstBalancer: HandleSubConnStateChange: 0xc4201580c0, CONNECTING
this is with default ticket buying turned off.
The client wallet should only be connecting to the server when it is buying a ticket. If the purchaseticket command has not been run, and the autobuyer is disabled, then it should not be connecting to the dcrtxmatcher server.

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/8ce2455bafd001d943ff2cdec6847d5273c86e3f, https://github.com/raedahgroup/dcrtxmatcher/commit/0a49ea1ae1965f53a0e547b649cb46d2ab50a22a and https://github.com/raedahgroup/dcrwallet/commit/5db3d8ff354b38372ad743e6b9cf54092cdfd061

**Comment by raedah** [comment]
verified resolved
