### ISSUE TITLE
Disconnect if solo participant

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#19]
If a client detects that their are no other participants in the join, instead of sending the transaction through the server, the client should instead disconnect and create a normal splittx locally without using the server.

**Comment by raedah** [comment]
In addition to the above safety check on the client to only go through the server if there are other participants, there should also be a min participants setting on the server. If the minimum number of participants are not connected to the server, the timer will not cause the transaction to be released and will instead wait until the minimum participants have connected.

**Comment by huyntsgs** [comment]
Fixed in above commits

**Comment by raedah** [comment]
Verified working.
