### ISSUE TITLE
Client does solo purchaseticket if server does not respond.

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#23]
If a purchase ticket does not happen with the server correct, it should fall back to doing a local solo purchaseticket. 

The client should have a timeout setting, for it the server is holding the connection open for x minutes and does create a join, the client can proceed with a solo ticket purchase.

**Comment by huyntsgs** [comment]
Fixed in above commits

**Comment by raedah** [comment]
Verified working.
