### ISSUE TITLE
Do not purchasetickets on client CTRL-C

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#27]
On the client when I CTRL-C to shut down while waiting for a join, instead of shutting downt he client, it quickly does a local purchase first and then shuts down. Instead, if CTRL-C is pushed on the client while waiting to buy tickets, it should shut down without buying any tickets.

[INF] DCRW: Received signal (interrupt).  Shutting down...
[INF] TKBY: Stopping ticket buyer
[INF] TXMA: dcrTxClient disconnected
[INF] GRPC: transport: loopyWriter.run returning. Err: connection error: desc = "transport is closing"
[INF] WLLT: Error in communication with dcrtxmatcher server, will buy locally

**Comment by huyntsgs** [comment]
Fixed in commit https://github.com/raedahgroup/dcrwallet/commit/19f0486285b32f077946fe1cc5ff847203e3c1ee

**Comment by raedah** [comment]
This will be put on hold for now because of the complications it creates with utxo selection.
