### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#28]
[x@rose dcrtxmatcher]$ ./dcrtxmatcher
2018-06-17 22:29:07.792 [INF] MATTX: MinParticipants 2
2018-06-17 22:29:07.792 [DBG] MATTX: Listening on :8475
2018-06-17 22:31:14.057 [INF] MATTX: SessionID bcje2cnsrhtmot90imh0 requests join
2018-06-17 22:31:14.639 [INF] MATTX: SessionID bcje2cnsrhtmot90imhg requests join
2018-06-17 22:34:01.018 [INF] MATTX: Participant disconnected. Removed sessionID bcje2cnsrhtmot90imh0 from waiting queue
2018-06-17 22:36:42.762 [INF] MATTX: Participant disconnected. Removed sessionID bcje2cnsrhtmot90imhg from waiting queue
2018-06-17 22:44:50.392 [INF] MATTX: SessionID bcje8onsrhtmot90imi0 requests join
2018-06-17 22:44:50.396 [INF] MATTX: SessionID bcje8onsrhtmot90imig requests join
2018-06-17 22:44:50.408 [INF] MATTX: SessionID bcje8onsrhtmot90imj0 requests join
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x82f8ba]

goroutine 14 [running]:
github.com/raedahgroup/dcrtxmatcher/daemon.(*SplitTxMatcherService).FindMatches(0xc4200a00d0, 0xaf4c00, 0xc42055c540, 0xc42009c260, 0xc4
200a00d0, 0x0, 0xc42059ba40)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/daemon/service.go:51 +0x34a
github.com/raedahgroup/dcrtxmatcher/api/matcherrpc._SplitTxMatcherService_FindMatches_Handler(0x8e1ca0, 0xc4200a00d0, 0xaf4c00, 0xc42055
c540, 0xc4200b0310, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/api/matcherrpc/api.pb.go:364 +0x241
github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420461e40, 0xaf66e0, 0xc420464300, 0xc420
566640, 0xc42012a9c0, 0xda3d80, 0x0, 0x0, 0x0)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc/server.go:921 +0x8ac
github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420461e40, 0xaf66e0, 0xc420464300, 0xc420566
640, 0x0)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc/server.go:1143 +0x1318
github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42058a010, 0xc420461e40, 0xaf66e0, 0
xc420464300, 0xc420566640)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/vendor/google.golang.org/grpc/server.go:636 +0xa1

**Comment by huyntsgs** [comment]
2018-06-06 21:57:09.662 [INF] MATTX: Sent joined transaction to all participants for purchasing tickets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5725d5]

goroutine 4267 [running]:
github.com/raedahgroup/dcrtxmatcher/vendor/github.com/decred/dcrd/wire.(*MsgTx).SerializeSize(0x0, 0xc4201e21c0)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/vendor/github.com/decred/dcrd/wire/msgtx.go:1184 +0x5
github.com/raedahgroup/dcrtxmatcher/daemon.(*SplitTxMatcherService).PublishResult.func1(0xc42069c2a0, 0xc4204f50b0, 0xc4201e6168, 0xc42000e0d0, 0xc4201e6170, 0x
c42015b270, 0xc4201e6178)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/daemon/service.go:200 +0x2a3
created by github.com/raedahgroup/dcrtxmatcher/daemon.(*SplitTxMatcherService).PublishResult
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/daemon/service.go:183 +0x114
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5725d5]

goroutine 4250 [running]:
github.com/raedahgroup/dcrtxmatcher/vendor/github.com/decred/dcrd/wire.(*MsgTx).SerializeSize(0x0, 0xc4206122a0)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/vendor/github.com/decred/dcrd/wire/msgtx.go:1184 +0x5
github.com/raedahgroup/dcrtxmatcher/daemon.(*SplitTxMatcherService).PublishResult.func1(0xc4205cc600, 0xc4201e50e0, 0xc42015e1d0, 0xc42000e0d0, 0xc42015e1d8, 0x
c42065b110, 0xc42015e1e8)
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/daemon/service.go:200 +0x2a3
created by github.com/raedahgroup/dcrtxmatcher/daemon.(*SplitTxMatcherService).PublishResult
        /home/x/go/src/github.com/raedahgroup/dcrtxmatcher/daemon/service.go:183 +0x114

**Comment by huyntsgs** [comment]
Fixed in commit https://github.com/raedahgroup/dcrtxmatcher/commit/f512168b8fe312c442d8dcb9476cf0e8a39e1081

**Comment by raedah** [comment]
verified
