### ISSUE TITLE
False success msg

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#29]
[INF] WLLT: Error in communication with dcrtxmatcher server, will buy locally
[INF] GRPC: pickfirstBalancer: HandleSubConnStateChange: 0xc42057e100, TRANSIENT_FAILURE
[INF] GRPC: pickfirstBalancer: HandleSubConnStateChange: 0xc42057e100, CONNECTING
[INF] GRPC: addrConn.createTransport failed to connect to {127.0.0.1:8475 0  <nil>}. Err :connection error: des
.0.0.1:8475: connect: connection refused". Reconnecting...
[INF] GRPC: pickfirstBalancer: HandleSubConnStateChange: 0xc42057e100, TRANSIENT_FAILURE
[INF] WLLT: Inserting unconfirmed transaction ebe99a64ea8e5041347f8606bc6a0b320188eb2d2fce2dc4b38c1f2c04c71127
[DBG] WLLT: Marked address TsXdL1phoaa22yMN353x9vQQTQXkvqfWueP used
[INF] WLLT: Successfully purchased and sent shared ticket transaction

The message "Successfully purchased and sent shared ticket transaction" is not accurate. An error is shown above saying that it is buying locally.

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrwallet/commit/6a785bba51ae589a25f2b6359a6c4aa6ffbd1c6c
