### ISSUE TITLE
cleanup logging

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#3]
Use the log pkg in dcrwallet to organize logging capabilities for the selected output level.

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/6f6007427ab8297a09216109e2b6ef8eebae48d3

**Comment by raedah** [comment]
Logging is improving. Will close this, and we can continue working on.
