### ISSUE TITLE
Purchase ticket locally when dcrtxmatcher is unavailable

### ISSUE THREAD

**Issue by huyntsgs** [raedahgroup/dcrtxmatcher#33]
Client should purchases locally when server is unavailable.

**Comment by raedah** [comment]
This appears to be working.
[INF] WLLT: Will do solo purchase ticket

This can be enhanced by settings a config variable on the client side which lets the clients choose how long they should wait for joined transaction to take place before they close the connection and do a solo purchase.

edit: this is being done as https://github.com/raedahgroup/dcrtxmatcher/issues/50
