### ISSUE TITLE
include txid in server log output

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#38]
[INF] DCMIX: Peer 2424728032 is random selected to publish tx

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrwallet/commit/f1424ff718b373041b9e223a7198ff5dc846ce2c

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/fbb7133ac06af6113e458a6e861805b89dd46dfc
