### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#40]
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9f413a, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc020000000, 0x4000000, 0x11d4cd8)
        /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x11bb3c0, 0x4000000, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x11bb3c0, 0x81, 0x0)
        /usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x11bb3c0, 0x81, 0x11d4ce8, 0x0)
        /usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x11bb3c0, 0x81, 0x101, 0xc59888)
        /usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x11bb3c0, 0x81, 0x7f10f1010101, 0x427910)
        /usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x10000e, 0x450101, 0xc01feb6000)
        /usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1229

goroutine 1138 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc01e67c8a0 sp=0xc01e67c898 pc=0x458330
runtime.mallocgc(0x10000e, 0x9197c0, 0x1, 0xc01feb6000)
        /usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc01e67c940 sp=0xc01e67c8a0 pc=0x40ecd6
runtime.makeslice(0x9197c0, 0x10000e, 0x10000e, 0xc01feb6000, 0x100000, 0x100000)
        /usr/local/go/src/runtime/slice.go:70 +0x77 fp=0xc01e67c970 sp=0xc01e67c940 pc=0x4435a7
github.com/gorilla/websocket.newConn(0xbcaa60, 0xc00000ede8, 0xc00005f901, 0x100000, 0x10000e, 0x0, 0x0, 0xc01636fa40, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:300 +0x2dc fp=0xc01e67ca38 sp=0xc01e67c970 pc=0x734b0c
github.com/gorilla/websocket.(*Upgrader).Upgrade(0xc01e67cc78, 0xbc8300, 0xc0000f2380, 0xc000268200, 0x0, 0x8000000000000000, 0xc01e67cc98, 0x48eec2)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/server.go:202 +0x540 fp=0xc01e67cc20 sp=0xc01e67ca38 pc=0x73ada0
main.run.func1(0xbc8300, 0xc0000f2380, 0xc000268200)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/dcrtxmatcher.go:62 +0xb0 fp=0xc01e67cce0 sp=0xc01e67cc20 pc=0x8be360
net/http.HandlerFunc.ServeHTTP(0xc00001fd80, 0xbc8300, 0xc0000f2380, 0xc000268200)
        /usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc01e67cd08 sp=0xc01e67cce0 pc=0x6eaec4
net/http.(*ServeMux).ServeHTTP(0x11b4b40, 0xbc8300, 0xc0000f2380, 0xc000268200)
        /usr/local/go/src/net/http/server.go:2361 +0x127 fp=0xc01e67cd48 sp=0xc01e67cd08 pc=0x6ecb57
net/http.serverHandler.ServeHTTP(0xc000078270, 0xbc8300, 0xc0000f2380, 0xc000268200)
        /usr/local/go/src/net/http/server.go:2741 +0xab fp=0xc01e67cd78 sp=0xc01e67cd48 pc=0x6edafb
net/http.(*conn).serve(0xc01a9ffcc0, 0xbc8940, 0xc00005f880)
        /usr/local/go/src/net/http/server.go:1847 +0x646 fp=0xc01e67cfc8 sp=0xc01e67cd78 pc=0x6e9f26
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc01e67cfd0 sp=0xc01e67cfc8 pc=0x45a411
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 1 [chan receive, 686 minutes]:
main.run(0xbc8940, 0xc00005e2c0, 0x0, 0x0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/dcrtxmatcher.go:137 +0x1e7
main.main()
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/dcrtxmatcher.go:24 +0x81

goroutine 6 [syscall, 686 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive, 686 minutes]:
main.withShutdownCancel.func1(0xc00001f680)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/signal.go:32 +0x36
created by main.withShutdownCancel
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/signal.go:31 +0x6b

goroutine 8 [select, 686 minutes]:
main.shutdownListener()
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/signal.go:52 +0x104
created by main.main
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/dcrtxmatcher.go:22 +0x69

goroutine 10 [select]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*DiceMix).Run(0xc00000d780, 0xc00000d720)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:140 +0xee
created by main.run
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/dcrtxmatcher.go:76 +0xa4d

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x7f10f7d16f00, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00008a018, 0x72, 0xc00005e000, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00008a018, 0xffffffffffffff00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc00008a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc00008a000, 0x40e72f, 0xc01a9ffcc0, 0xa0)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000e010, 0xc000051e10, 0x352df03f, 0x7229cab0197d3661)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).AcceptTCP(0xc00000e010, 0xc000051e38, 0x486536, 0x5bf3b496)
        /usr/local/go/src/net/tcpsock.go:247 +0x47
net/http.tcpKeepAliveListener.Accept(0xc00000e010, 0xc000051e88, 0x18, 0xc00047a000, 0x6ee035)
        /usr/local/go/src/net/http/server.go:3232 +0x2f
net/http.(*Server).Serve(0xc000078270, 0xbc87c0, 0xc00000e010, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2826 +0x22f
net/http.(*Server).ListenAndServe(0xc000078270, 0xc000078270, 0x0)
        /usr/local/go/src/net/http/server.go:2764 +0xb6
net/http.ListenAndServe(0xc00002abc8, 0x5, 0x0, 0x0, 0x5, 0x0)
        /usr/local/go/src/net/http/server.go:3004 +0x74
created by main.run
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/dcrtxmatcher.go:81 +0xbcd

goroutine 44 [chan receive, 659 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc0004117a0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 16 [chan receive, 684 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc000410120)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 26 [chan receive, 674 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc0004106c0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 21 [chan receive, 684 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc000410240)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 35 [chan receive, 668 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc0004118c0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 30 [chan receive, 674 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc0004107e0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 80 [chan receive, 634 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc00010ca20)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 39 [chan receive, 668 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc000410b40)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 62 [chan receive, 652 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc00010c000)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 48 [chan receive, 659 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc0004119e0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

....

goroutine 1096 [chan receive, 15 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01b81fd40)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 1105 [chan receive, 10 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01b81f9e0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 1114 [chan receive, 8 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01a7ec480)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 1123 [chan receive, 6 minutes]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01a7ec240)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 1130 [chan receive]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01a7ec6c0)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 1132 [chan receive]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01a7ec900)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

goroutine 1136 [chan receive]:
github.com/raedahgroup/dcrtxmatcher/coinjoin.(*PeerInfo).WriteMessages(0xc01a7eca20)
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:260 +0x87
created by github.com/raedahgroup/dcrtxmatcher/coinjoin.(*JoinQueue).AddNewPeer
        /root/go/src/github.com/raedahgroup/dcrtxmatcher/coinjoin/coinjoin.go:232 +0x27b

**Comment by raedah** [comment]
This seems to have been resolved in https://github.com/raedahgroup/dcrtxmatcher/commit/775f1016daa6004736465c4032155b2375b3dcf7

**Comment by huyntsgs** [comment]
This is fixed by the commit you mentioned. Still needs to check for long running time (one week or more)
