### ISSUE TITLE
utxos marked as used when sharedtx failed

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#45]
im seeing a number of these on the client log
error purchasing ticket... err: -4: dcrd.jsonrpc.sendrawtransaction: -40: Rejected transaction 8d3e1edcd169bc9bc9179ffd1592339cf2683e11361f51387dbc73a6ed8f7cf2
: orphan transaction 8d3e1edcd169bc9bc9179ffd1592339cf2683e11361f51387dbc73a6ed8f7cf2 references outputs of unknown or fully-spent transaction 78f3027da0eabd78
bf442af14760a24c26c21207b30e223c6189ead2dd3d9031

It may be being caused the dcrwallet marking an input used by a transaction when actually the transaction failed and was never broadcast or perhaps never even signed by the client.

**Comment by huyntsgs** [comment]
Client may purchase ticket before join tx is inserted to mempool. Fix in this commit https://github.com/raedahgroup/dcrwallet/commit/f42ce43dee3b461cbed9e81e19061594bf96a9d3
