### ISSUE TITLE
randomize output order

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#5]
Output order on the shared split transaction is in a predictable order. The order of the outputs should be randomized.  This can be a toggle-able option for debuging purposes.

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/8ce2455bafd001d943ff2cdec6847d5273c86e3f, https://github.com/raedahgroup/dcrtxmatcher/commit/0a49ea1ae1965f53a0e547b649cb46d2ab50a22a and https://github.com/raedahgroup/dcrwallet/commit/5db3d8ff354b38372ad743e6b9cf54092cdfd061

**Comment by raedah** [comment]
verified working
