### ISSUE TITLE
Fail with purchaseticket default 99 2

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#6]
purchaseticket default 99 2
The 2 is numtickets.

 err: SSgen tx has an invalid number of inputs

publishTx error -1: Rejected transaction 28fcbccb48e41264cc8d0603ef84c581f3a48e2f0ed8c388c67abe149f925a22: Tx 28fcbccb48e41264cc8d0603ef84c581f3a48e2f0ed8c388c
67abe149f925a22 attempted to spend an OP_SSTX tagged output, however it was not an SSGen or SSRtx tx; SSGen err: SSgen tx has an invalid number of inputs, SSRt
x err: SSRtx has an  invalid number of inputs

-1: Rejected transaction 28fcbccb48e41264cc8d0603ef84c581f3a48e2f0ed8c388c67abe149f925a22: Tx 28fcbccb48e41264cc8d0603ef84c581f3a48e2f0ed8c388c67abe149f925a22
attempted to spend an OP_SSTX tagged output, however it was not an SSGen or SSRtx tx; SSGen err: SSgen tx has an invalid number of inputs, SSRtx err: SSRtx has
 an  invalid number of inputs

**Comment by huyntsgs** [comment]
Fix in this commit https://github.com/raedahgroup/dcrwallet/commit/b0b1341f4a4894df0325aab61f97afa5c2429852

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrtxmatcher/commit/6f6007427ab8297a09216109e2b6ef8eebae48d3 and https://github.com/raedahgroup/dcrwallet/commit/f59cbe0c0cf37e18a427c89b1850c2407687e606

**Comment by raedah** [comment]
Tested working.
